variables:
  APP_ENV: 'test'

.ui: &ui
  image: ruby:2.3
  before_script:
    - cd ui && bundle install --path vendor --retry 3 --jobs 3
  cache:
    key: 'reddit-ui-4'
    paths:
      - ui/vendor

stages:
  - lint
  - test
  - build
  - deploy

ui:rubocop:
  <<: *ui
  stage: lint
  script:
    - bundle exec rubocop
  allow_failure: true

ui:test:
  <<: *ui
  stage: test
  script:
    - bundle exec ruby ui_test.rb

ui:build:
  <<: *ui
  stage: build
  script:
    - echo 'Building'
  only:
    - tags

ui:deploy:
  <<: *ui
  stage: deploy
  script:
    - echo 'Deploy'
  only:
    - tags
