Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
