source "https://rubygems.org"

gem "sinatra", "~> 2.0.2"
gem "sinatra-contrib", "~> 2.0.2"

gem "bson_ext"
gem "faraday"
gem "haml"
gem "prometheus-client"
gem "puma"
gem "rack", ">= 2.0.6"
gem "rufus-scheduler"
gem "tzinfo-data"
gem "zipkin-tracer"

gem "rack-test"
gem "rubocop", "~> 0.65.0", :require => false
gem "test-unit"
