source "https://rubygems.org"

gem "sinatra", "~> 2.0.2"
gem "sinatra-contrib", "~> 2.0.2"

gem "bson_ext"
gem "haml"
gem "puma"
gem "rest-client"

gem "rack-test"
gem 'test-unit'
gem "rubocop", "~> 0.65.0", :require => false
